### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by maicol07** [RedFantom/ttkthemes#14]
Hi, when I set up a Style in a window the normal font changes. In my case, from the standard Windows one it switches to the Ubuntu one... how to fix this?
Here you can see text in Label and Button (Ubuntu font) and the one in the window title and the text in the combobox (MS Font).

![immagine](https://user-images.githubusercontent.com/9463142/38240441-e3dc8212-372f-11e8-91a4-ad50fa6abc20.png)
Thanks

**Comment by RedFantom** [comment]
Upon enabling a theme, the style defined for each particular widget can override all options, including the font. If you would like to specify a particular font for each widget, most ttk widgets support the `font` keyword argument. This accepts a `tkinter.font.Font` instance or a font tuple (like `("Consolas", 12)`).

If you would like to change the default behaviour instead of specifying the font for each widget, you can override the font option in the style for each widget. For some basic information about this, I suggest reading [this](http://infohost.nmt.edu/tcc/help/pubs/tkinter/web/ttk-style-layer.html) page.

**Comment by maicol07** [comment]
Thanks! It works with `s.configure(".", font="Helvetica")`
