### ISSUE TITLE
ttkthemes depends on numpy

### ISSUE THREAD

**Issue by Akuli** [RedFantom/ttkthemes#16]
There are a couple reasons why I don't like having this awesome library depend on numpy:

- numpy is a big library and importing it slows down the startup of my application.
- I'm running Python 3.7 and numpy doesn't compile on Python 3.7 yet, so I'm stuck on an old version of ttkthemes.

Grepping the source code, I noticed that numpy is used only for *one* image processing function. Please use a list comprehension or something instead. Pillow doesn't depend on numpy either, so a collection of ttk themes should really be just fine without it IMO.

**Comment by RedFantom** [comment]
In response to your request, I have performed some performance profiling using the code in the new `numpy` branch. For reference, I have performed these tests on a system with the following specifications:
```
Intel Core i7 6700HQ
8GiB DDR4 memory
256GB NVMe SSD
```

Initiallly, I had chosen to use `numpy` because the compiled `numpy` library is generally much, much faster at performing even simple numeric operations in Python, and because the `pillow` library is compatible with it. After these results, however, I am reconsidering:
```
shift_hue:       24ms  27ms  28ms
shift_hue_numpy: 19ms  14ms 14ms
```
This means that using plain Python is significantly slower than using `numpy`, but the numeric difference is generally negligible. Even when importing the module at the top of the file instead of using a lazy import does not seem to have much of an impact:
```
examply.py, theme arc, no advanced theme
with_numpy:    276ms  288ms  273ms
without_numpy: 285ms  294ms  286ms
```
To me, that all seems to be within the margin of error. The import does not significantly slow down the starting of the `example.py` script.

My conclusion is that the usage of the `numpy` library does not significantly impact the performance of the library, and given how it is only used in a single function, it is best to remove the dependency entirely.

**Comment by Akuli** [comment]
I agree, especially because import time actually **does** matter in my application...

**Comment by Akuli** [comment]
Ummm... a clarification: without an ssd, the import time is bigger, and it's biggest when numpy is imported for the first time after a reboot. Even if python is restarted, linux is caching numpy's files in ram and they load a lot faster.

**Comment by RedFantom** [comment]
Yes, I can imagine. Using an SSD minimizes seek times, which are especially large when performing imports that might be fragmented and all over a physical disk if it is used.

I am first investigating this issue though:
```python
AssertionError: (255, 0, 0, 255) == (255, 0, 0, 255)
```

**Comment by Akuli** [comment]
Now the numpy branch is merged, so I'll close this. Thanks!

**Comment by RedFantom** [comment]
Thank you for pointing this out to me!
