### ISSUE TITLE
Create Toplevel hook to set background to default Frame background

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/ttkthemes#31]
Currently, `Toplevel` widgets have their default background color for all themes. It would be better if each `Toplevel` opened were to have its background color set by default to the background color of a `ttk.Frame`. This could be implemented with something like:

```python
def setup_toplevel_background():
    color = ttk.Style().lookup("TFrame", "background", default="white")
    __init__orig = tk.Toplevel.__init__
    
    def __init__hook(*args, **kwargs):
        kwargs.setdefault("background", color)
        __init__orig(*args, **kwargs)
    
    tk.Toplevel.__init__ = __init__hook
```

**Comment by Akuli** [comment]
The standard solution is to add a `ttk.Frame` inside every toplevel window in the application, and that's a recommended thing to do in ttk. I have done that ever since I started using ttk, and at least tkdocs does that. Maybe mention it in the docs and call it done?

**Comment by RedFantom** [comment]
That might be the recommended way to do things for the `ttk` library, but using a hook instead would allow `ttkthemes` to really be a drop-in replacement, which is what I was aiming for (Just replace `Tk` with `ThemedTk` and run a replace from `tk` to `ttk` and you're done).

**Comment by Akuli** [comment]
I don't really want ttkthemes to be a "drop-in replacement" to ttk. I don't want it to be any kind of "replacement" because I don't like the idea of replacing ttk with something else. I'm not one of those people (do they even exist?) who find it nice to just change this and that and it works. I have a big project that creates a bunch of ttk widgets before even importing ttkthemes, and I want future versions of ttkthemes support using it that way (that is, with `ThemedStyle`).

So, if you add some `Toplevel` magic that breaks my code by making **all** Toplevels behave differently, at least don't make ttkthemes do that magic by default, or, at the *very* least add an option to turn off the magic.

**Comment by RedFantom** [comment]
I was planning on adding an option to turn off the magic, at least. `ttkthemes` is not meant to replace `ttk`, but `ThemedTk` is meant to replace `tkinter.Tk`. `ThemedStyle` will not have the option to setup the hook on initialization.

Though, in my goal implementation the Toplevels would not quite behave differently. The Toplevels would only change their default background color. If the programmer specified a background color, it would still take on that color.

I do appreciate your point of critique though. In fact, all your comments make me strive to make this a better library. Just thought you should know that.

If you still disagree after this explanation, I'd also love to hear.

**Comment by Akuli** [comment]
Sounds good to me. Will the hook setup code go to `ThemedTk.__init__` so that if `ThemedTk` objects are never created, the hook won't be installed?

**Comment by Akuli** [comment]
I just read your comment again a bit more carefully, and you mentioned that it will. Awesome :)

**Comment by RedFantom** [comment]
Merged!
