### ISSUE TITLE
Unable to import ttkthemes module

### ISSUE THREAD

**Issue by NRG-600** [RedFantom/ttkthemes#36]
I installed ttkthemes through help of pip. 
It get install perfectly but i'm unable to import it.

It just showing error about multiple sub-modules of ttkthemes.

![error](https://user-images.githubusercontent.com/37657519/41866303-5a862722-78cd-11e8-91f2-269ac0ea414a.PNG)

**Comment by RedFantom** [comment]
Unfortunately, that is not an issue I can fix, as it's an issue with your `pillow` installation. `pillow` is the library that `ttkthemes` uses to perform image manipulations to support dynamic themeing. The import of the `pillow` (or its internal name `PIL`, as it's actually a fork of that library) is failing because some sub-module is missing.

My suggestion would be to reinstall `pillow`. I see you are using Anaconda, and I have not personally tested either pillow or ttkthemes on that platform, but for a normal Python installation, the snippet below should do the trick.
```bash
python -m pip uninstall ttkthemes
python -m pip install -U ttkthemes
```

**Comment by Akuli** [comment]
`pip uninstall` does not uninstall the dependencies.

**Comment by RedFantom** [comment]
@Akuli You are correct. I mistakenly wrote `ttkthemes` in the `pip` commands, even though I intended to write `pillow` instead. :sweat:

**Comment by Akuli** [comment]
Uninstalling pillow *does* uninstall ttkthemes because ttkthemes depends on it :D

**Comment by NRG-600** [comment]
I tried to reinstall pillow and ttkthemes but still it showing same error as i mentioned above. 
How can i solve this...? I really want to use this theme in my current python project.

You're right i use Anaconda it's running in Windows 7 SP1 Machine.

**Comment by RedFantom** [comment]
In that case, the issue may lay in the `pillow` packages published on Python, or there is some weird issue with your Python installation. I cannot determine the issue for you. Your best bet is first checking if you can make `pillow` work in a completely different Python installation, and if you can reproduce the issue, to open an issue in the [`pillow`](https://github.com/python-pillow/Pillow/issues) repository.

**Comment by testlol12345** [comment]
Hey try installing using pip3
